# Tensor Flow

TensorFlow™ is an open source software library for high performance numerical computation. Its flexible architecture allows easy deployment of computation across a variety of platforms (CPUs, GPUs, TPUs), and from desktops to clusters of servers to mobile and edge devices. Originally developed by researchers and engineers from the Google Brain team within Google’s AI organization, it comes with strong support for machine learning and deep learning and the flexible numerical computation core is used across many other scientific domains.

## Create operations

In [6]:
import tensorflow as tf

# Create a 1x2 matrix
matrix1 = tf.constant([[3., 3.]])

# Create a 2x1 matrix
matrix2 = tf.constant([[2.],[2.]])

# multiplication
product = tf.matmul(matrix1, matrix2)


Here tensorflow does not `run` the calculations but only create a set of operations.

## Run the operations in a session

In [7]:
# Start a session
sess = tf.Session()

# 'run(product)' to do all the operations contained in the product
# 'result' numpy `ndarray` object
result = sess.run(product)
print(result)
# ==> [[ 12.]]

# Close the session
sess.close()

[[12.]]


In [9]:
# Session must be closed to release resources
# You can use `with` to do this automatically
with tf.Session() as sess:
  result = sess.run(product)
  print(result)

[[12.]]


TensorFlow automatically selects which devices to use for the caculations. Normally if the machine has GPUs, it will try to use the first one it finds.
It also allows you select which device to use by yourself.

```
with tf.Session() as sess:
  with tf.device("/gpu:1"):
    matrix1 = tf.constant([[3., 3.]])
    matrix2 = tf.constant([[2.],[2.]])
    product = tf.matmul(matrix1, matrix2)
    ...
```

Supported devices:
 - "/cpu:0": CPU.
 - "/gpu:0": The first GPU, if exists
 - "/gpu:1": The second GPU, etc

In [3]:
# list available devices
from tensorflow.python.client import device_lib

def get_available_devices():
    local_device_protos = device_lib.list_local_devices()
    return [(x.name, x.device_type) for x in local_device_protos]

print(get_available_devices())

[('/device:CPU:0', 'CPU')]


## Tensor

TensorFlow sees tensor as a `n` dimentional array or list.

A tensor contains a `rank` and a `shape`.


## Variable

Variables store the states of a running graph.

The follwing example shows how to implement a simple counter with variables.

In [20]:
# create a variable op
state = tf.Variable(0, name="counter")

# create more ops, which adds 1 to the existing value
one = tf.constant(1)
new_value = tf.add(state, one)
update = tf.assign(state, new_value)

# init the variable 
init_op = tf.initialize_all_variables()

# start the session
with tf.Session() as sess:
  # run with the init_op
  sess.run(init_op)
  # print the init state
  print(sess.run(state))
  # run update op and print the state
  for _ in range(3):
    sess.run(update)
    print(sess.run(state))

0
1
2
3


Normally the parameters of a statistics model can be stored into variables. For example, the weights of a neural network can be put into a tensor variable, which can be updated during training.

## Feed

Feed is like `local variables`. It releases after the operation.

Warning: "Feeding" is the least efficient way to feed data into a TensorFlow program and should only be used for small experiments and debugging.

In [26]:
x = tf.placeholder(tf.float32, shape=(1024, 1024))
y = tf.matmul(x, x)

with tf.Session() as sess:
#   print(sess.run(y))  # ERROR: will fail because x was not fed.

  rand_array = np.random.rand(1024, 1024)
  print(sess.run(y, feed_dict={x: rand_array}))  # Will succeed.

[[271.7932  262.925   260.3382  ... 267.51035 271.60425 271.18796]
 [258.6997  254.5677  258.29233 ... 260.52664 262.65033 261.86035]
 [252.65413 248.1597  246.60962 ... 253.30356 258.7171  256.05878]
 ...
 [241.45462 235.8337  244.81593 ... 247.6417  246.75197 243.59348]
 [258.55606 244.85881 249.97055 ... 254.2782  253.41292 253.65778]
 [254.52028 251.21689 262.70874 ... 257.1659  254.47882 262.87305]]
